tags:
  label: dimsog.blog::lang.controllers.posts.tags
  manage:
    list: $/dimsog/blog/models/posttag/columns.yaml
    form: $/dimsog/blog/models/posttag/fields.yaml
  view:
    list: $/dimsog/blog/models/posttag/columns.yaml
    toolbarButtons:
      create: dimsog.blog::lang.controllers.common.create
      delete: dimsog.blog::lang.controllers.common.delete
cards:
  label: dimsog.blog::lang.controllers.posts.cards
  deferredBinding: true
  manage:
    list: $/dimsog/blog/models/postcard/columns.yaml
    form: $/dimsog/blog/models/postcard/fields.yaml
  view:
    list: $/dimsog/blog/models/postcard/columns.yaml
    toolbarButtons:
      create: dimsog.blog::lang.controllers.common.create
      delete: dimsog.blog::lang.controllers.common.delete
